# Generated by Django 4.1.7 on 2023-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
