# Generated by Django 4.1.7 on 2023-03-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_onetimeuselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
