# Generated by Django 4.1.7 on 2023-04-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
