# Generated by Django 4.1.7 on 2023-04-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='recordings/')),
            ],
        ),
    ]
