# Generated by Django 4.1.7 on 2023-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_doctorschedule_doctorappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_start_time',
            field=models.DateField(),
        ),
    ]
