# Generated by Django 4.1.7 on 2023-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_doctorappointment_date_doctorschedule_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_start_time',
            field=models.DateField(),
        ),
    ]
