# Generated by Django 4.1.7 on 2023-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_remove_doctorappointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_start_time',
            field=models.DateTimeField(),
        ),
    ]
