# Generated by Django 4.1.7 on 2023-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_alter_doctorappointment_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField()),
            ],
        ),
    ]
