# Generated by Django 4.1.7 on 2023-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nps',
            field=models.FloatField(default=0),
        ),
    ]
