# Generated by Django 4.1.7 on 2023-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_nps_remove_feedback_nps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='nps',
            field=models.IntegerField(default=0),
        ),
    ]
